### ISSUE TITLE
Add check that file was not added

### ISSUE THREAD

**Issue by ai** [pshergie/pull-request-auto-reviewer#11]
Use case:

> I want to add “Add tests” message if user change `core/*.ts` but don’t change anything in `core/test/*.test.ts`

So I suggest something like:

```yaml
    - paths: 'core/*.ts'
      missed: 'core/test/*.test.ts'
      message: |
        - [ ] Don’t rush. Check all changes in PR again.
        - [ ] Run `pnpm test`.
```
